version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db-new
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network
    ports:
      - "3306:3306"

  node-api:
    build: .
    container_name: node-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend-network
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb

volumes:
  db_data:

networks:
  backend-network:
    driver: bridge

